// The signaling channel between peersh clients and the signaling server runs
// over WebSocket. Each WebSocket binary message carries exactly one
// Frame protobuf, which is a oneof of all the message types the channel can
// produce.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: peersh/signal/v1/frame.proto

package signalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Frame is the single envelope for every signaling message. The receiver
// dispatches on the populated oneof variant.
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Frame_ClientHello
	//	*Frame_ServerHello
	//	*Frame_Register
	//	*Frame_RegisterAck
	//	*Frame_Connect
	//	*Frame_ServerError
	Body          isFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_peersh_signal_v1_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_signal_v1_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_peersh_signal_v1_frame_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetBody() isFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Frame) GetClientHello() *ClientHello {
	if x != nil {
		if x, ok := x.Body.(*Frame_ClientHello); ok {
			return x.ClientHello
		}
	}
	return nil
}

func (x *Frame) GetServerHello() *ServerHello {
	if x != nil {
		if x, ok := x.Body.(*Frame_ServerHello); ok {
			return x.ServerHello
		}
	}
	return nil
}

func (x *Frame) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Body.(*Frame_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *Frame) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Body.(*Frame_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *Frame) GetConnect() *Connect {
	if x != nil {
		if x, ok := x.Body.(*Frame_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *Frame) GetServerError() *ServerError {
	if x != nil {
		if x, ok := x.Body.(*Frame_ServerError); ok {
			return x.ServerError
		}
	}
	return nil
}

type isFrame_Body interface {
	isFrame_Body()
}

type Frame_ClientHello struct {
	ClientHello *ClientHello `protobuf:"bytes,1,opt,name=client_hello,json=clientHello,proto3,oneof"`
}

type Frame_ServerHello struct {
	ServerHello *ServerHello `protobuf:"bytes,2,opt,name=server_hello,json=serverHello,proto3,oneof"`
}

type Frame_Register struct {
	Register *Register `protobuf:"bytes,3,opt,name=register,proto3,oneof"`
}

type Frame_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,4,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type Frame_Connect struct {
	Connect *Connect `protobuf:"bytes,5,opt,name=connect,proto3,oneof"`
}

type Frame_ServerError struct {
	ServerError *ServerError `protobuf:"bytes,6,opt,name=server_error,json=serverError,proto3,oneof"`
}

func (*Frame_ClientHello) isFrame_Body() {}

func (*Frame_ServerHello) isFrame_Body() {}

func (*Frame_Register) isFrame_Body() {}

func (*Frame_RegisterAck) isFrame_Body() {}

func (*Frame_Connect) isFrame_Body() {}

func (*Frame_ServerError) isFrame_Body() {}

var File_peersh_signal_v1_frame_proto protoreflect.FileDescriptor

const file_peersh_signal_v1_frame_proto_rawDesc = "" +
	"\n" +
	"\x1cpeersh/signal/v1/frame.proto\x12\x10peersh.signal.v1\x1a\x1fpeersh/signal/v1/messages.proto\"\x90\x03\n" +
	"\x05Frame\x12B\n" +
	"\fclient_hello\x18\x01 \x01(\v2\x1d.peersh.signal.v1.ClientHelloH\x00R\vclientHello\x12B\n" +
	"\fserver_hello\x18\x02 \x01(\v2\x1d.peersh.signal.v1.ServerHelloH\x00R\vserverHello\x128\n" +
	"\bregister\x18\x03 \x01(\v2\x1a.peersh.signal.v1.RegisterH\x00R\bregister\x12B\n" +
	"\fregister_ack\x18\x04 \x01(\v2\x1d.peersh.signal.v1.RegisterAckH\x00R\vregisterAck\x125\n" +
	"\aconnect\x18\x05 \x01(\v2\x19.peersh.signal.v1.ConnectH\x00R\aconnect\x12B\n" +
	"\fserver_error\x18\x06 \x01(\v2\x1d.peersh.signal.v1.ServerErrorH\x00R\vserverErrorB\x06\n" +
	"\x04bodyB\xc6\x01\n" +
	"\x14com.peersh.signal.v1B\n" +
	"FrameProtoP\x01Z@github.com/peersh/peersh/core/protocol/peersh/signal/v1;signalv1\xa2\x02\x03PSX\xaa\x02\x10Peersh.Signal.V1\xca\x02\x10Peersh\\Signal\\V1\xe2\x02\x1cPeersh\\Signal\\V1\\GPBMetadata\xea\x02\x12Peersh::Signal::V1b\x06proto3"

var (
	file_peersh_signal_v1_frame_proto_rawDescOnce sync.Once
	file_peersh_signal_v1_frame_proto_rawDescData []byte
)

func file_peersh_signal_v1_frame_proto_rawDescGZIP() []byte {
	file_peersh_signal_v1_frame_proto_rawDescOnce.Do(func() {
		file_peersh_signal_v1_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peersh_signal_v1_frame_proto_rawDesc), len(file_peersh_signal_v1_frame_proto_rawDesc)))
	})
	return file_peersh_signal_v1_frame_proto_rawDescData
}

var file_peersh_signal_v1_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_peersh_signal_v1_frame_proto_goTypes = []any{
	(*Frame)(nil),       // 0: peersh.signal.v1.Frame
	(*ClientHello)(nil), // 1: peersh.signal.v1.ClientHello
	(*ServerHello)(nil), // 2: peersh.signal.v1.ServerHello
	(*Register)(nil),    // 3: peersh.signal.v1.Register
	(*RegisterAck)(nil), // 4: peersh.signal.v1.RegisterAck
	(*Connect)(nil),     // 5: peersh.signal.v1.Connect
	(*ServerError)(nil), // 6: peersh.signal.v1.ServerError
}
var file_peersh_signal_v1_frame_proto_depIdxs = []int32{
	1, // 0: peersh.signal.v1.Frame.client_hello:type_name -> peersh.signal.v1.ClientHello
	2, // 1: peersh.signal.v1.Frame.server_hello:type_name -> peersh.signal.v1.ServerHello
	3, // 2: peersh.signal.v1.Frame.register:type_name -> peersh.signal.v1.Register
	4, // 3: peersh.signal.v1.Frame.register_ack:type_name -> peersh.signal.v1.RegisterAck
	5, // 4: peersh.signal.v1.Frame.connect:type_name -> peersh.signal.v1.Connect
	6, // 5: peersh.signal.v1.Frame.server_error:type_name -> peersh.signal.v1.ServerError
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_peersh_signal_v1_frame_proto_init() }
func file_peersh_signal_v1_frame_proto_init() {
	if File_peersh_signal_v1_frame_proto != nil {
		return
	}
	file_peersh_signal_v1_messages_proto_init()
	file_peersh_signal_v1_frame_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_ClientHello)(nil),
		(*Frame_ServerHello)(nil),
		(*Frame_Register)(nil),
		(*Frame_RegisterAck)(nil),
		(*Frame_Connect)(nil),
		(*Frame_ServerError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peersh_signal_v1_frame_proto_rawDesc), len(file_peersh_signal_v1_frame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peersh_signal_v1_frame_proto_goTypes,
		DependencyIndexes: file_peersh_signal_v1_frame_proto_depIdxs,
		MessageInfos:      file_peersh_signal_v1_frame_proto_msgTypes,
	}.Build()
	File_peersh_signal_v1_frame_proto = out.File
	file_peersh_signal_v1_frame_proto_goTypes = nil
	file_peersh_signal_v1_frame_proto_depIdxs = nil
}
