// Signaling channel messages. Carried inside Frame.body (see frame.proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: peersh/signal/v1/messages.proto

package signalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviceKind tags whether a registered device is a Windows host, a mobile
// client, or a developer CLI. Mirrors core/store.DeviceKind plus a CLI value
// used during Phase 2 / development.
type DeviceKind int32

const (
	DeviceKind_DEVICE_KIND_UNSPECIFIED   DeviceKind = 0
	DeviceKind_DEVICE_KIND_WINDOWS_HOST  DeviceKind = 1
	DeviceKind_DEVICE_KIND_MOBILE_CLIENT DeviceKind = 2
	DeviceKind_DEVICE_KIND_CLI           DeviceKind = 3
)

// Enum value maps for DeviceKind.
var (
	DeviceKind_name = map[int32]string{
		0: "DEVICE_KIND_UNSPECIFIED",
		1: "DEVICE_KIND_WINDOWS_HOST",
		2: "DEVICE_KIND_MOBILE_CLIENT",
		3: "DEVICE_KIND_CLI",
	}
	DeviceKind_value = map[string]int32{
		"DEVICE_KIND_UNSPECIFIED":   0,
		"DEVICE_KIND_WINDOWS_HOST":  1,
		"DEVICE_KIND_MOBILE_CLIENT": 2,
		"DEVICE_KIND_CLI":           3,
	}
)

func (x DeviceKind) Enum() *DeviceKind {
	p := new(DeviceKind)
	*p = x
	return p
}

func (x DeviceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_peersh_signal_v1_messages_proto_enumTypes[0].Descriptor()
}

func (DeviceKind) Type() protoreflect.EnumType {
	return &file_peersh_signal_v1_messages_proto_enumTypes[0]
}

func (x DeviceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceKind.Descriptor instead.
func (DeviceKind) EnumDescriptor() ([]byte, []int) {
	return file_peersh_signal_v1_messages_proto_rawDescGZIP(), []int{0}
}

// CandidateType tags how the candidate address was obtained.
//
// Phase 2 only emits HOST. SERVER_REFLEXIVE is reserved for Phase 3 (STUN);
// PEER_REFLEXIVE may be added later.
type CandidateType int32

const (
	CandidateType_CANDIDATE_TYPE_UNSPECIFIED      CandidateType = 0
	CandidateType_CANDIDATE_TYPE_HOST             CandidateType = 1
	CandidateType_CANDIDATE_TYPE_SERVER_REFLEXIVE CandidateType = 2
	CandidateType_CANDIDATE_TYPE_PEER_REFLEXIVE   CandidateType = 3
)

// Enum value maps for CandidateType.
var (
	CandidateType_name = map[int32]string{
		0: "CANDIDATE_TYPE_UNSPECIFIED",
		1: "CANDIDATE_TYPE_HOST",
		2: "CANDIDATE_TYPE_SERVER_REFLEXIVE",
		3: "CANDIDATE_TYPE_PEER_REFLEXIVE",
	}
	CandidateType_value = map[string]int32{
		"CANDIDATE_TYPE_UNSPECIFIED":      0,
		"CANDIDATE_TYPE_HOST":             1,
		"CANDIDATE_TYPE_SERVER_REFLEXIVE": 2,
		"CANDIDATE_TYPE_PEER_REFLEXIVE":   3,
	}
)

func (x CandidateType) Enum() *CandidateType {
	p := new(CandidateType)
	*p = x
	return p
}

func (x CandidateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CandidateType) Descriptor() protoreflect.EnumDescriptor {
	return file_peersh_signal_v1_messages_proto_enumTypes[1].Descriptor()
}

func (CandidateType) Type() protoreflect.EnumType {
	return &file_peersh_signal_v1_messages_proto_enumTypes[1]
}

func (x CandidateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CandidateType.Descriptor instead.
func (CandidateType) EnumDescriptor() ([]byte, []int) {
	return file_peersh_signal_v1_messages_proto_rawDescGZIP(), []int{1}
}

// ClientHello opens a WebSocket signaling connection. Sent once, immediately
// after the WebSocket upgrade completes.
type ClientHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ClientId        string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_peersh_signal_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_signal_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_peersh_signal_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ClientHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ClientHello) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// ServerHello is the server's reply on the same channel.
type ServerHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ServerId        string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_peersh_signal_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_signal_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_peersh_signal_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ServerHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ServerHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ServerHello) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

// Register is the PSK-signed initial registration sent by the client right
// after the Hello exchange.
//
// HMAC verification: marshal this message deterministically with
// hmac_signature cleared, then HMAC-SHA256 with the user's PSK secret.
// Server verifies by repeating the process and comparing with hmac.Equal.
type Register struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UserId      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId    string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PublicKey   []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Kind        DeviceKind             `protobuf:"varint,4,opt,name=kind,proto3,enum=peersh.signal.v1.DeviceKind" json:"kind,omitempty"`
	DisplayName string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Authenticator fields. signed_at_unix and nonce defend against replay;
	// hmac_signature is the verifier.
	SignedAtUnix  int64  `protobuf:"varint,10,opt,name=signed_at_unix,json=signedAtUnix,proto3" json:"signed_at_unix,omitempty"`
	Nonce         []byte `protobuf:"bytes,11,opt,name=nonce,proto3" json:"nonce,omitempty"`
	HmacSignature []byte `protobuf:"bytes,12,opt,name=hmac_signature,json=hmacSignature,proto3" json:"hmac_signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_peersh_signal_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_signal_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_peersh_signal_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Register) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Register) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Register) GetKind() DeviceKind {
	if x != nil {
		return x.Kind
	}
	return DeviceKind_DEVICE_KIND_UNSPECIFIED
}

func (x *Register) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Register) GetSignedAtUnix() int64 {
	if x != nil {
		return x.SignedAtUnix
	}
	return 0
}

func (x *Register) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Register) GetHmacSignature() []byte {
	if x != nil {
		return x.HmacSignature
	}
	return nil
}

// RegisterAck is the server's response to Register.
type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_peersh_signal_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_signal_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_peersh_signal_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RegisterAck) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

// EndpointCandidate is one address a peer can be reached at.
type EndpointCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Type          CandidateType          `protobuf:"varint,3,opt,name=type,proto3,enum=peersh.signal.v1.CandidateType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointCandidate) Reset() {
	*x = EndpointCandidate{}
	mi := &file_peersh_signal_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointCandidate) ProtoMessage() {}

func (x *EndpointCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_signal_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointCandidate.ProtoReflect.Descriptor instead.
func (*EndpointCandidate) Descriptor() ([]byte, []int) {
	return file_peersh_signal_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *EndpointCandidate) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EndpointCandidate) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EndpointCandidate) GetType() CandidateType {
	if x != nil {
		return x.Type
	}
	return CandidateType_CANDIDATE_TYPE_UNSPECIFIED
}

// Connect is the endpoint-exchange message. Used in both directions:
//
//   - Initiator → server: target_device_id is set. The server forwards to
//     that target with from_device_id populated.
//   - Server → target: target_device_id is the recipient (= self), and
//     from_device_id is the initiator.
//   - Target → initiator (via server): same shape with target_device_id =
//     initiator, from_device_id = target. Server forwards.
//
// The server fills from_device_id from the authenticated session; clients
// must leave it empty when sending.
type Connect struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetDeviceId string                 `protobuf:"bytes,1,opt,name=target_device_id,json=targetDeviceId,proto3" json:"target_device_id,omitempty"`
	FromDeviceId   string                 `protobuf:"bytes,2,opt,name=from_device_id,json=fromDeviceId,proto3" json:"from_device_id,omitempty"`
	Candidates     []*EndpointCandidate   `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Connect) Reset() {
	*x = Connect{}
	mi := &file_peersh_signal_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect) ProtoMessage() {}

func (x *Connect) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_signal_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect.ProtoReflect.Descriptor instead.
func (*Connect) Descriptor() ([]byte, []int) {
	return file_peersh_signal_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Connect) GetTargetDeviceId() string {
	if x != nil {
		return x.TargetDeviceId
	}
	return ""
}

func (x *Connect) GetFromDeviceId() string {
	if x != nil {
		return x.FromDeviceId
	}
	return ""
}

func (x *Connect) GetCandidates() []*EndpointCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

// ServerError reports that something went wrong. The connection may or may
// not stay open depending on code semantics.
type ServerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerError) Reset() {
	*x = ServerError{}
	mi := &file_peersh_signal_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerError) ProtoMessage() {}

func (x *ServerError) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_signal_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerError.ProtoReflect.Descriptor instead.
func (*ServerError) Descriptor() ([]byte, []int) {
	return file_peersh_signal_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ServerError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ServerError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_peersh_signal_v1_messages_proto protoreflect.FileDescriptor

const file_peersh_signal_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1fpeersh/signal/v1/messages.proto\x12\x10peersh.signal.v1\"y\n" +
	"\vClientHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"y\n" +
	"\vServerHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\"\x97\x02\n" +
	"\bRegister\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x120\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1c.peersh.signal.v1.DeviceKindR\x04kind\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12$\n" +
	"\x0esigned_at_unix\x18\n" +
	" \x01(\x03R\fsignedAtUnix\x12\x14\n" +
	"\x05nonce\x18\v \x01(\fR\x05nonce\x12%\n" +
	"\x0ehmac_signature\x18\f \x01(\fR\rhmacSignature\"^\n" +
	"\vRegisterAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\"v\n" +
	"\x11EndpointCandidate\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x123\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1f.peersh.signal.v1.CandidateTypeR\x04type\"\x9e\x01\n" +
	"\aConnect\x12(\n" +
	"\x10target_device_id\x18\x01 \x01(\tR\x0etargetDeviceId\x12$\n" +
	"\x0efrom_device_id\x18\x02 \x01(\tR\ffromDeviceId\x12C\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2#.peersh.signal.v1.EndpointCandidateR\n" +
	"candidates\";\n" +
	"\vServerError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*{\n" +
	"\n" +
	"DeviceKind\x12\x1b\n" +
	"\x17DEVICE_KIND_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DEVICE_KIND_WINDOWS_HOST\x10\x01\x12\x1d\n" +
	"\x19DEVICE_KIND_MOBILE_CLIENT\x10\x02\x12\x13\n" +
	"\x0fDEVICE_KIND_CLI\x10\x03*\x90\x01\n" +
	"\rCandidateType\x12\x1e\n" +
	"\x1aCANDIDATE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CANDIDATE_TYPE_HOST\x10\x01\x12#\n" +
	"\x1fCANDIDATE_TYPE_SERVER_REFLEXIVE\x10\x02\x12!\n" +
	"\x1dCANDIDATE_TYPE_PEER_REFLEXIVE\x10\x03B\xc9\x01\n" +
	"\x14com.peersh.signal.v1B\rMessagesProtoP\x01Z@github.com/peersh/peersh/core/protocol/peersh/signal/v1;signalv1\xa2\x02\x03PSX\xaa\x02\x10Peersh.Signal.V1\xca\x02\x10Peersh\\Signal\\V1\xe2\x02\x1cPeersh\\Signal\\V1\\GPBMetadata\xea\x02\x12Peersh::Signal::V1b\x06proto3"

var (
	file_peersh_signal_v1_messages_proto_rawDescOnce sync.Once
	file_peersh_signal_v1_messages_proto_rawDescData []byte
)

func file_peersh_signal_v1_messages_proto_rawDescGZIP() []byte {
	file_peersh_signal_v1_messages_proto_rawDescOnce.Do(func() {
		file_peersh_signal_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peersh_signal_v1_messages_proto_rawDesc), len(file_peersh_signal_v1_messages_proto_rawDesc)))
	})
	return file_peersh_signal_v1_messages_proto_rawDescData
}

var file_peersh_signal_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_peersh_signal_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_peersh_signal_v1_messages_proto_goTypes = []any{
	(DeviceKind)(0),           // 0: peersh.signal.v1.DeviceKind
	(CandidateType)(0),        // 1: peersh.signal.v1.CandidateType
	(*ClientHello)(nil),       // 2: peersh.signal.v1.ClientHello
	(*ServerHello)(nil),       // 3: peersh.signal.v1.ServerHello
	(*Register)(nil),          // 4: peersh.signal.v1.Register
	(*RegisterAck)(nil),       // 5: peersh.signal.v1.RegisterAck
	(*EndpointCandidate)(nil), // 6: peersh.signal.v1.EndpointCandidate
	(*Connect)(nil),           // 7: peersh.signal.v1.Connect
	(*ServerError)(nil),       // 8: peersh.signal.v1.ServerError
}
var file_peersh_signal_v1_messages_proto_depIdxs = []int32{
	0, // 0: peersh.signal.v1.Register.kind:type_name -> peersh.signal.v1.DeviceKind
	1, // 1: peersh.signal.v1.EndpointCandidate.type:type_name -> peersh.signal.v1.CandidateType
	6, // 2: peersh.signal.v1.Connect.candidates:type_name -> peersh.signal.v1.EndpointCandidate
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_peersh_signal_v1_messages_proto_init() }
func file_peersh_signal_v1_messages_proto_init() {
	if File_peersh_signal_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peersh_signal_v1_messages_proto_rawDesc), len(file_peersh_signal_v1_messages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peersh_signal_v1_messages_proto_goTypes,
		DependencyIndexes: file_peersh_signal_v1_messages_proto_depIdxs,
		EnumInfos:         file_peersh_signal_v1_messages_proto_enumTypes,
		MessageInfos:      file_peersh_signal_v1_messages_proto_msgTypes,
	}.Build()
	File_peersh_signal_v1_messages_proto = out.File
	file_peersh_signal_v1_messages_proto_goTypes = nil
	file_peersh_signal_v1_messages_proto_depIdxs = nil
}
