// Per-command (and per-PTY) bidi streams opened after the control stream's
// Hello handshake completes.
//
// Every fresh stream begins with a StreamRequest envelope so the server can
// dispatch between the one-shot Exec path (Phase 1) and the interactive PTY
// path (Phase 8). The two paths share the underlying QUIC transport but
// have distinct response shapes.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: peersh/v1/exec.proto

package peershv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamRequest is the first frame on a fresh stream. The populated `kind`
// determines how the server treats subsequent frames on the stream.
type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*StreamRequest_Exec
	//	*StreamRequest_Pty
	//	*StreamRequest_Files
	Kind          isStreamRequest_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_peersh_v1_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetKind() isStreamRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *StreamRequest) GetExec() *ExecRequest {
	if x != nil {
		if x, ok := x.Kind.(*StreamRequest_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *StreamRequest) GetPty() *PTYRequest {
	if x != nil {
		if x, ok := x.Kind.(*StreamRequest_Pty); ok {
			return x.Pty
		}
	}
	return nil
}

func (x *StreamRequest) GetFiles() *FilesRequest {
	if x != nil {
		if x, ok := x.Kind.(*StreamRequest_Files); ok {
			return x.Files
		}
	}
	return nil
}

type isStreamRequest_Kind interface {
	isStreamRequest_Kind()
}

type StreamRequest_Exec struct {
	Exec *ExecRequest `protobuf:"bytes,1,opt,name=exec,proto3,oneof"`
}

type StreamRequest_Pty struct {
	Pty *PTYRequest `protobuf:"bytes,2,opt,name=pty,proto3,oneof"`
}

type StreamRequest_Files struct {
	Files *FilesRequest `protobuf:"bytes,3,opt,name=files,proto3,oneof"`
}

func (*StreamRequest_Exec) isStreamRequest_Kind() {}

func (*StreamRequest_Pty) isStreamRequest_Kind() {}

func (*StreamRequest_Files) isStreamRequest_Kind() {}

// ExecRequest runs a single command and streams its output back. Used by
// peersh-cli's prompt loop and the mobile app's text viewer (ReadFile is
// implemented as Exec under the hood).
type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command is the PowerShell expression to execute. Treated as a single
	// pipeline; the host appends a sentinel marker to detect completion.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// working_dir, if non-empty, is set as the current working directory for
	// this command only. Empty means "use the session's current directory".
	// Reserved in Phase 1; implemented by the cwd-aware ReadFile path in
	// Phase 8 Tier 2.
	WorkingDir    string `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_peersh_v1_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{1}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

// ExecResponse carries either a chunk of output or the end-of-command signal.
// One ExecRequest produces a stream of ExecResponse messages, with the final
// message having done = true.
type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chunk holds streamed output bytes. Exactly one of stdout / stderr is set
	// on any non-final message; both may be unset on the final done = true
	// message.
	//
	// Types that are valid to be assigned to Chunk:
	//
	//	*ExecResponse_Stdout
	//	*ExecResponse_Stderr
	Chunk isExecResponse_Chunk `protobuf_oneof:"chunk"`
	// done signals end-of-command. The stream is closed after this message.
	Done          bool `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_peersh_v1_exec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{2}
}

func (x *ExecResponse) GetChunk() isExecResponse_Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Chunk.(*ExecResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Chunk.(*ExecResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type isExecResponse_Chunk interface {
	isExecResponse_Chunk()
}

type ExecResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

func (*ExecResponse_Stdout) isExecResponse_Chunk() {}

func (*ExecResponse_Stderr) isExecResponse_Chunk() {}

// PTYRequest opens a pseudo-console-backed shell or program on the host.
// After the server acks (by starting to send PTYData frames), the client
// streams keystrokes as PTYInput frames and resize notifications as
// PTYResize frames; the server streams PTYData frames carrying raw output
// (ANSI sequences and all) and finally a single PTYExit terminator.
type PTYRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command, when non-empty, is the executable to spawn (e.g. "claude").
	// Empty means "use the operator-configured default shell" — usually
	// pwsh wrapped with the OSC 9;9 prompt instrumentation.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// args are the command-line arguments passed verbatim. Ignored when
	// command is empty (the server picks the default shell wrapper).
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// cols and rows are the initial terminal grid the client wants the
	// pseudo-console sized to.
	Cols uint32 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows uint32 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	// env carries supplementary environment variables (e.g. TERM=xterm-256color).
	// The host process inherits the peershd environment plus these overrides.
	Env map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// pty_id is a client-chosen handle that becomes the lookup key for
	// the file-API requests (FilesRequest.{Get,List,Read}*). Must be
	// unique within this QUIC connection. Tier 2 — clients that don't
	// care about the file API may leave it 0; the file API will refuse
	// to resolve pty_id=0.
	PtyId int64 `protobuf:"varint,6,opt,name=pty_id,json=ptyId,proto3" json:"pty_id,omitempty"`
	// reattach_handle, when non-empty, requests reattaching to a
	// previously-opened persisted PTY identified by this server-assigned
	// handle. command / args / env are ignored for reattach (the
	// existing child keeps running); cols / rows are honoured (they
	// resize the existing PTY). The server replies with a
	// PTYReattachAck frame as the first server-bound frame, followed by
	// the scrollback replay as PTYData chunks. Phase 6b Tier 2.
	ReattachHandle string `protobuf:"bytes,7,opt,name=reattach_handle,json=reattachHandle,proto3" json:"reattach_handle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PTYRequest) Reset() {
	*x = PTYRequest{}
	mi := &file_peersh_v1_exec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYRequest) ProtoMessage() {}

func (x *PTYRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYRequest.ProtoReflect.Descriptor instead.
func (*PTYRequest) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{3}
}

func (x *PTYRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *PTYRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *PTYRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PTYRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *PTYRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *PTYRequest) GetPtyId() int64 {
	if x != nil {
		return x.PtyId
	}
	return 0
}

func (x *PTYRequest) GetReattachHandle() string {
	if x != nil {
		return x.ReattachHandle
	}
	return ""
}

// PTYReattachAck is the first server-bound frame on a reattach stream.
// It tells the client whether the requested handle was attached (and
// the new server-assigned handle, in case the client needs to refresh
// its stored copy). After ack, the server flushes the scrollback ring
// buffer as zero or more PTYData frames in chronological order, then
// resumes live PTY data flow.
type PTYReattachAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// handle is the server-assigned reattach handle. For a fresh PTY
	// that just got persisted, this is the newly-issued handle. For a
	// successful reattach this echoes the request's reattach_handle.
	Handle string `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// accepted is false when the requested handle is unknown or expired.
	// Multiple clients may attach to the same handle simultaneously
	// (multi-attach fan-out), so "already attached" is no longer a
	// failure mode. When accepted=false the rest of the stream carries
	// a final PTYExit and closes.
	Accepted bool `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// reason is human-readable text when accepted=false.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYReattachAck) Reset() {
	*x = PTYReattachAck{}
	mi := &file_peersh_v1_exec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYReattachAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYReattachAck) ProtoMessage() {}

func (x *PTYReattachAck) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYReattachAck.ProtoReflect.Descriptor instead.
func (*PTYReattachAck) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{4}
}

func (x *PTYReattachAck) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *PTYReattachAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PTYReattachAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PTYInput delivers a chunk of bytes from the user's keyboard / paste
// buffer to the child process's stdin.
type PTYInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYInput) Reset() {
	*x = PTYInput{}
	mi := &file_peersh_v1_exec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYInput) ProtoMessage() {}

func (x *PTYInput) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYInput.ProtoReflect.Descriptor instead.
func (*PTYInput) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{5}
}

func (x *PTYInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PTYResize tells the child the terminal grid dimensions changed.
// Programs that re-flow on SIGWINCH (or its Windows equivalent) react.
type PTYResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYResize) Reset() {
	*x = PTYResize{}
	mi := &file_peersh_v1_exec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYResize) ProtoMessage() {}

func (x *PTYResize) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYResize.ProtoReflect.Descriptor instead.
func (*PTYResize) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{6}
}

func (x *PTYResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PTYResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// PTYData carries raw output bytes from the child's pseudo-console.
// ConPTY merges stdout/stderr into a single byte stream, so unlike
// ExecResponse there is no separate channel tagging.
type PTYData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYData) Reset() {
	*x = PTYData{}
	mi := &file_peersh_v1_exec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYData) ProtoMessage() {}

func (x *PTYData) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYData.ProtoReflect.Descriptor instead.
func (*PTYData) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{7}
}

func (x *PTYData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PTYExit terminates the PTY stream. After PTYExit the server closes the
// stream and any further client frames are discarded.
type PTYExit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// exit_code mirrors the child process's exit status. -1 indicates an
	// unknown / abnormal exit (e.g. peersh killed the process to satisfy
	// an idle timeout).
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// error, when non-empty, describes a server-side failure (spawn error,
	// pseudo-console allocation failure, ...).
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYExit) Reset() {
	*x = PTYExit{}
	mi := &file_peersh_v1_exec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYExit) ProtoMessage() {}

func (x *PTYExit) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYExit.ProtoReflect.Descriptor instead.
func (*PTYExit) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{8}
}

func (x *PTYExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *PTYExit) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PTYFrame multiplexes the direction-specific message types onto the
// single QUIC stream. Client → server frames use the input / resize /
// notification_config fields; server → client frames use the data /
// exit / reattach_ack fields.
type PTYFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*PTYFrame_Input
	//	*PTYFrame_Resize
	//	*PTYFrame_Data
	//	*PTYFrame_Exit
	//	*PTYFrame_ReattachAck
	//	*PTYFrame_NotificationConfig
	Kind          isPTYFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYFrame) Reset() {
	*x = PTYFrame{}
	mi := &file_peersh_v1_exec_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYFrame) ProtoMessage() {}

func (x *PTYFrame) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYFrame.ProtoReflect.Descriptor instead.
func (*PTYFrame) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{9}
}

func (x *PTYFrame) GetKind() isPTYFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *PTYFrame) GetInput() *PTYInput {
	if x != nil {
		if x, ok := x.Kind.(*PTYFrame_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *PTYFrame) GetResize() *PTYResize {
	if x != nil {
		if x, ok := x.Kind.(*PTYFrame_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *PTYFrame) GetData() *PTYData {
	if x != nil {
		if x, ok := x.Kind.(*PTYFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *PTYFrame) GetExit() *PTYExit {
	if x != nil {
		if x, ok := x.Kind.(*PTYFrame_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

func (x *PTYFrame) GetReattachAck() *PTYReattachAck {
	if x != nil {
		if x, ok := x.Kind.(*PTYFrame_ReattachAck); ok {
			return x.ReattachAck
		}
	}
	return nil
}

func (x *PTYFrame) GetNotificationConfig() *PTYNotificationConfig {
	if x != nil {
		if x, ok := x.Kind.(*PTYFrame_NotificationConfig); ok {
			return x.NotificationConfig
		}
	}
	return nil
}

type isPTYFrame_Kind interface {
	isPTYFrame_Kind()
}

type PTYFrame_Input struct {
	Input *PTYInput `protobuf:"bytes,1,opt,name=input,proto3,oneof"`
}

type PTYFrame_Resize struct {
	Resize *PTYResize `protobuf:"bytes,2,opt,name=resize,proto3,oneof"`
}

type PTYFrame_Data struct {
	Data *PTYData `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type PTYFrame_Exit struct {
	Exit *PTYExit `protobuf:"bytes,4,opt,name=exit,proto3,oneof"`
}

type PTYFrame_ReattachAck struct {
	ReattachAck *PTYReattachAck `protobuf:"bytes,5,opt,name=reattach_ack,json=reattachAck,proto3,oneof"`
}

type PTYFrame_NotificationConfig struct {
	NotificationConfig *PTYNotificationConfig `protobuf:"bytes,6,opt,name=notification_config,json=notificationConfig,proto3,oneof"`
}

func (*PTYFrame_Input) isPTYFrame_Kind() {}

func (*PTYFrame_Resize) isPTYFrame_Kind() {}

func (*PTYFrame_Data) isPTYFrame_Kind() {}

func (*PTYFrame_Exit) isPTYFrame_Kind() {}

func (*PTYFrame_ReattachAck) isPTYFrame_Kind() {}

func (*PTYFrame_NotificationConfig) isPTYFrame_Kind() {}

// PTYNotificationConfig (client → server) toggles per-PTY push-
// notification behavior on the host. v2-B uses this to opt the
// individual terminal tab into command-completion alerts.
type PTYNotificationConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enabled gates all notifications from this PTY. When false, the
	// host does not write any RTDB notification doc regardless of
	// OSC 9;9 detection or idle silence.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// threshold_seconds is the minimum elapsed time between a user-
	// typed command starting and the next prompt OSC 9;9 firing
	// before a notification is dispatched. Default 10 s; commands
	// shorter than this don't notify.
	ThresholdSeconds uint32 `protobuf:"varint,2,opt,name=threshold_seconds,json=thresholdSeconds,proto3" json:"threshold_seconds,omitempty"`
	// idle_seconds enables the output-silence heuristic for non-shell
	// tools (Claude / Codex / etc.) that don't emit OSC 9;9 prompt
	// markers. When the PTY's stdout has been silent for this many
	// seconds AND a command is still considered running, the host
	// dispatches a single notification. 0 disables the heuristic
	// entirely.
	IdleSeconds uint32 `protobuf:"varint,3,opt,name=idle_seconds,json=idleSeconds,proto3" json:"idle_seconds,omitempty"`
	// tab_label is the human-readable label the mobile client uses
	// for this PTY tab. The host echoes it into the notification body
	// so the user sees which tab finished.
	TabLabel string `protobuf:"bytes,4,opt,name=tab_label,json=tabLabel,proto3" json:"tab_label,omitempty"`
	// mobile_device_id is the UUID the mobile app generated and
	// registered against RTDB at users/{uid}/devices/{mobile_device_id}/
	// fcm_token. The host writes this into the RTDB notification doc;
	// the Cloud Function uses it to look up the FCM token to dispatch
	// to. Must be present for notifications to fire.
	MobileDeviceId string `protobuf:"bytes,5,opt,name=mobile_device_id,json=mobileDeviceId,proto3" json:"mobile_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PTYNotificationConfig) Reset() {
	*x = PTYNotificationConfig{}
	mi := &file_peersh_v1_exec_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYNotificationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYNotificationConfig) ProtoMessage() {}

func (x *PTYNotificationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYNotificationConfig.ProtoReflect.Descriptor instead.
func (*PTYNotificationConfig) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{10}
}

func (x *PTYNotificationConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PTYNotificationConfig) GetThresholdSeconds() uint32 {
	if x != nil {
		return x.ThresholdSeconds
	}
	return 0
}

func (x *PTYNotificationConfig) GetIdleSeconds() uint32 {
	if x != nil {
		return x.IdleSeconds
	}
	return 0
}

func (x *PTYNotificationConfig) GetTabLabel() string {
	if x != nil {
		return x.TabLabel
	}
	return ""
}

func (x *PTYNotificationConfig) GetMobileDeviceId() string {
	if x != nil {
		return x.MobileDeviceId
	}
	return ""
}

type FilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*FilesRequest_GetSession
	//	*FilesRequest_ListFiles
	//	*FilesRequest_ReadFile
	//	*FilesRequest_ListPtys
	//	*FilesRequest_KillPty
	Kind          isFilesRequest_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesRequest) Reset() {
	*x = FilesRequest{}
	mi := &file_peersh_v1_exec_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesRequest) ProtoMessage() {}

func (x *FilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesRequest.ProtoReflect.Descriptor instead.
func (*FilesRequest) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{11}
}

func (x *FilesRequest) GetKind() isFilesRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *FilesRequest) GetGetSession() *GetSessionRequest {
	if x != nil {
		if x, ok := x.Kind.(*FilesRequest_GetSession); ok {
			return x.GetSession
		}
	}
	return nil
}

func (x *FilesRequest) GetListFiles() *ListSessionFilesRequest {
	if x != nil {
		if x, ok := x.Kind.(*FilesRequest_ListFiles); ok {
			return x.ListFiles
		}
	}
	return nil
}

func (x *FilesRequest) GetReadFile() *ReadSessionFileRequest {
	if x != nil {
		if x, ok := x.Kind.(*FilesRequest_ReadFile); ok {
			return x.ReadFile
		}
	}
	return nil
}

func (x *FilesRequest) GetListPtys() *ListPTYsRequest {
	if x != nil {
		if x, ok := x.Kind.(*FilesRequest_ListPtys); ok {
			return x.ListPtys
		}
	}
	return nil
}

func (x *FilesRequest) GetKillPty() *KillPTYRequest {
	if x != nil {
		if x, ok := x.Kind.(*FilesRequest_KillPty); ok {
			return x.KillPty
		}
	}
	return nil
}

type isFilesRequest_Kind interface {
	isFilesRequest_Kind()
}

type FilesRequest_GetSession struct {
	GetSession *GetSessionRequest `protobuf:"bytes,1,opt,name=get_session,json=getSession,proto3,oneof"`
}

type FilesRequest_ListFiles struct {
	ListFiles *ListSessionFilesRequest `protobuf:"bytes,2,opt,name=list_files,json=listFiles,proto3,oneof"`
}

type FilesRequest_ReadFile struct {
	ReadFile *ReadSessionFileRequest `protobuf:"bytes,3,opt,name=read_file,json=readFile,proto3,oneof"`
}

type FilesRequest_ListPtys struct {
	ListPtys *ListPTYsRequest `protobuf:"bytes,4,opt,name=list_ptys,json=listPtys,proto3,oneof"`
}

type FilesRequest_KillPty struct {
	KillPty *KillPTYRequest `protobuf:"bytes,5,opt,name=kill_pty,json=killPty,proto3,oneof"`
}

func (*FilesRequest_GetSession) isFilesRequest_Kind() {}

func (*FilesRequest_ListFiles) isFilesRequest_Kind() {}

func (*FilesRequest_ReadFile) isFilesRequest_Kind() {}

func (*FilesRequest_ListPtys) isFilesRequest_Kind() {}

func (*FilesRequest_KillPty) isFilesRequest_Kind() {}

type FilesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error, when non-empty, indicates the request failed and the other
	// payload fields are unset.
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*FilesResponse_GetSession
	//	*FilesResponse_ListFiles
	//	*FilesResponse_ReadFile
	//	*FilesResponse_ListPtys
	//	*FilesResponse_KillPty
	Payload       isFilesResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesResponse) Reset() {
	*x = FilesResponse{}
	mi := &file_peersh_v1_exec_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesResponse) ProtoMessage() {}

func (x *FilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesResponse.ProtoReflect.Descriptor instead.
func (*FilesResponse) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{12}
}

func (x *FilesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FilesResponse) GetPayload() isFilesResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FilesResponse) GetGetSession() *GetSessionResponse {
	if x != nil {
		if x, ok := x.Payload.(*FilesResponse_GetSession); ok {
			return x.GetSession
		}
	}
	return nil
}

func (x *FilesResponse) GetListFiles() *ListSessionFilesResponse {
	if x != nil {
		if x, ok := x.Payload.(*FilesResponse_ListFiles); ok {
			return x.ListFiles
		}
	}
	return nil
}

func (x *FilesResponse) GetReadFile() *ReadSessionFileResponse {
	if x != nil {
		if x, ok := x.Payload.(*FilesResponse_ReadFile); ok {
			return x.ReadFile
		}
	}
	return nil
}

func (x *FilesResponse) GetListPtys() *ListPTYsResponse {
	if x != nil {
		if x, ok := x.Payload.(*FilesResponse_ListPtys); ok {
			return x.ListPtys
		}
	}
	return nil
}

func (x *FilesResponse) GetKillPty() *KillPTYResponse {
	if x != nil {
		if x, ok := x.Payload.(*FilesResponse_KillPty); ok {
			return x.KillPty
		}
	}
	return nil
}

type isFilesResponse_Payload interface {
	isFilesResponse_Payload()
}

type FilesResponse_GetSession struct {
	GetSession *GetSessionResponse `protobuf:"bytes,2,opt,name=get_session,json=getSession,proto3,oneof"`
}

type FilesResponse_ListFiles struct {
	ListFiles *ListSessionFilesResponse `protobuf:"bytes,3,opt,name=list_files,json=listFiles,proto3,oneof"`
}

type FilesResponse_ReadFile struct {
	ReadFile *ReadSessionFileResponse `protobuf:"bytes,4,opt,name=read_file,json=readFile,proto3,oneof"`
}

type FilesResponse_ListPtys struct {
	ListPtys *ListPTYsResponse `protobuf:"bytes,5,opt,name=list_ptys,json=listPtys,proto3,oneof"`
}

type FilesResponse_KillPty struct {
	KillPty *KillPTYResponse `protobuf:"bytes,6,opt,name=kill_pty,json=killPty,proto3,oneof"`
}

func (*FilesResponse_GetSession) isFilesResponse_Payload() {}

func (*FilesResponse_ListFiles) isFilesResponse_Payload() {}

func (*FilesResponse_ReadFile) isFilesResponse_Payload() {}

func (*FilesResponse_ListPtys) isFilesResponse_Payload() {}

func (*FilesResponse_KillPty) isFilesResponse_Payload() {}

// KillPTYRequest tears down a persisted PTY by its reattach handle.
// Unlike a stream close (which detaches but keeps the PTY alive for
// the idle TTL), KillPTY closes the underlying child process and
// drops the ring buffer immediately. Phase 6b Tier 2.
type KillPTYRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillPTYRequest) Reset() {
	*x = KillPTYRequest{}
	mi := &file_peersh_v1_exec_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillPTYRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillPTYRequest) ProtoMessage() {}

func (x *KillPTYRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillPTYRequest.ProtoReflect.Descriptor instead.
func (*KillPTYRequest) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{13}
}

func (x *KillPTYRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type KillPTYResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillPTYResponse) Reset() {
	*x = KillPTYResponse{}
	mi := &file_peersh_v1_exec_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillPTYResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillPTYResponse) ProtoMessage() {}

func (x *KillPTYResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillPTYResponse.ProtoReflect.Descriptor instead.
func (*KillPTYResponse) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{14}
}

func (x *KillPTYResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// ListPTYsRequest enumerates persisted PTYs the connected client may
// reattach to. There are no parameters today — peersh's per-connection
// Manager scope means the response naturally only includes this
// client's own PTYs. Phase 6b Tier 2.
type ListPTYsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPTYsRequest) Reset() {
	*x = ListPTYsRequest{}
	mi := &file_peersh_v1_exec_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPTYsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPTYsRequest) ProtoMessage() {}

func (x *ListPTYsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPTYsRequest.ProtoReflect.Descriptor instead.
func (*ListPTYsRequest) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{15}
}

type PTYHandle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// handle is the server-assigned reattach handle.
	Handle string `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// command is what the PTY is running (diagnostic; "auto" / "pwsh" /
	// "claude" / ...). May be empty for default shells.
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// attached is true when at least one stream is currently bound.
	// Retained for back-compat with older clients; new clients should
	// prefer attached_count for richer UI ("3 clients connected").
	Attached bool `protobuf:"varint,3,opt,name=attached,proto3" json:"attached,omitempty"`
	// cwd is the most recent directory the host observed (via OSC 9;9).
	// Empty until the prompt has rendered at least once.
	Cwd string `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// last_seen_unix_ms is the wall-clock time of the most recent
	// attach/detach transition.
	LastSeenUnixMs int64 `protobuf:"varint,5,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	// attached_count is the number of streams currently bound to this
	// PTY. Zero means detached (TTL countdown active). Multiple means
	// several clients are observing the same shell live (multi-attach).
	AttachedCount uint32 `protobuf:"varint,6,opt,name=attached_count,json=attachedCount,proto3" json:"attached_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYHandle) Reset() {
	*x = PTYHandle{}
	mi := &file_peersh_v1_exec_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYHandle) ProtoMessage() {}

func (x *PTYHandle) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYHandle.ProtoReflect.Descriptor instead.
func (*PTYHandle) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{16}
}

func (x *PTYHandle) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *PTYHandle) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *PTYHandle) GetAttached() bool {
	if x != nil {
		return x.Attached
	}
	return false
}

func (x *PTYHandle) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *PTYHandle) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

func (x *PTYHandle) GetAttachedCount() uint32 {
	if x != nil {
		return x.AttachedCount
	}
	return 0
}

type ListPTYsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ptys          []*PTYHandle           `protobuf:"bytes,1,rep,name=ptys,proto3" json:"ptys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPTYsResponse) Reset() {
	*x = ListPTYsResponse{}
	mi := &file_peersh_v1_exec_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPTYsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPTYsResponse) ProtoMessage() {}

func (x *ListPTYsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPTYsResponse.ProtoReflect.Descriptor instead.
func (*ListPTYsResponse) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{17}
}

func (x *ListPTYsResponse) GetPtys() []*PTYHandle {
	if x != nil {
		return x.Ptys
	}
	return nil
}

type GetSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pty_id identifies the live PTY whose cwd to report.
	PtyId         int64 `protobuf:"varint,1,opt,name=pty_id,json=ptyId,proto3" json:"pty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_peersh_v1_exec_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{18}
}

func (x *GetSessionRequest) GetPtyId() int64 {
	if x != nil {
		return x.PtyId
	}
	return 0
}

type GetSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cwd is the last directory observed in the shell's prompt OSC 9;9
	// sequence. Empty until the prompt has rendered at least once.
	Cwd           string `protobuf:"bytes,1,opt,name=cwd,proto3" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_peersh_v1_exec_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{19}
}

func (x *GetSessionResponse) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

type ListSessionFilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	PtyId int64                  `protobuf:"varint,1,opt,name=pty_id,json=ptyId,proto3" json:"pty_id,omitempty"`
	// path is resolved against the session's cwd. Empty means cwd itself.
	// Forward slashes and back slashes are both accepted.
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionFilesRequest) Reset() {
	*x = ListSessionFilesRequest{}
	mi := &file_peersh_v1_exec_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionFilesRequest) ProtoMessage() {}

func (x *ListSessionFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionFilesRequest.ProtoReflect.Descriptor instead.
func (*ListSessionFilesRequest) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{20}
}

func (x *ListSessionFilesRequest) GetPtyId() int64 {
	if x != nil {
		return x.PtyId
	}
	return 0
}

func (x *ListSessionFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// path is the cwd-relative path of this entry, suitable for passing
	// back as ListSessionFilesRequest.path or ReadSessionFileRequest.path.
	Path  string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	IsDir bool   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size  int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// modified_unix_ms is the file's modification time in unix milliseconds.
	ModifiedUnixMs int64 `protobuf:"varint,5,opt,name=modified_unix_ms,json=modifiedUnixMs,proto3" json:"modified_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_peersh_v1_exec_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{21}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetModifiedUnixMs() int64 {
	if x != nil {
		return x.ModifiedUnixMs
	}
	return 0
}

type ListSessionFilesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// resolved_path is the canonicalised cwd-relative path the host
	// actually listed (after collapsing redundant separators).
	ResolvedPath  string       `protobuf:"bytes,1,opt,name=resolved_path,json=resolvedPath,proto3" json:"resolved_path,omitempty"`
	Entries       []*FileEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionFilesResponse) Reset() {
	*x = ListSessionFilesResponse{}
	mi := &file_peersh_v1_exec_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionFilesResponse) ProtoMessage() {}

func (x *ListSessionFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionFilesResponse.ProtoReflect.Descriptor instead.
func (*ListSessionFilesResponse) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{22}
}

func (x *ListSessionFilesResponse) GetResolvedPath() string {
	if x != nil {
		return x.ResolvedPath
	}
	return ""
}

func (x *ListSessionFilesResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ReadSessionFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	PtyId int64                  `protobuf:"varint,1,opt,name=pty_id,json=ptyId,proto3" json:"pty_id,omitempty"`
	Path  string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// max_bytes caps the response size. 0 -> server default (4 MiB).
	MaxBytes      int64 `protobuf:"varint,3,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSessionFileRequest) Reset() {
	*x = ReadSessionFileRequest{}
	mi := &file_peersh_v1_exec_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSessionFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSessionFileRequest) ProtoMessage() {}

func (x *ReadSessionFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSessionFileRequest.ProtoReflect.Descriptor instead.
func (*ReadSessionFileRequest) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{23}
}

func (x *ReadSessionFileRequest) GetPtyId() int64 {
	if x != nil {
		return x.PtyId
	}
	return 0
}

func (x *ReadSessionFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadSessionFileRequest) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type ReadSessionFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Encoding      string                 `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding,omitempty"`    // "utf-8", "utf-8-bom", "utf-16-le", ...
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`           // total file size on disk
	Truncated     bool                   `protobuf:"varint,4,opt,name=truncated,proto3" json:"truncated,omitempty"` // content was clipped to max_bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSessionFileResponse) Reset() {
	*x = ReadSessionFileResponse{}
	mi := &file_peersh_v1_exec_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSessionFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSessionFileResponse) ProtoMessage() {}

func (x *ReadSessionFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSessionFileResponse.ProtoReflect.Descriptor instead.
func (*ReadSessionFileResponse) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{24}
}

func (x *ReadSessionFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ReadSessionFileResponse) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *ReadSessionFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ReadSessionFileResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

var File_peersh_v1_exec_proto protoreflect.FileDescriptor

const file_peersh_v1_exec_proto_rawDesc = "" +
	"\n" +
	"\x14peersh/v1/exec.proto\x12\tpeersh.v1\"\xa1\x01\n" +
	"\rStreamRequest\x12,\n" +
	"\x04exec\x18\x01 \x01(\v2\x16.peersh.v1.ExecRequestH\x00R\x04exec\x12)\n" +
	"\x03pty\x18\x02 \x01(\v2\x15.peersh.v1.PTYRequestH\x00R\x03pty\x12/\n" +
	"\x05files\x18\x03 \x01(\v2\x17.peersh.v1.FilesRequestH\x00R\x05filesB\x06\n" +
	"\x04kind\"H\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\"_\n" +
	"\fExecResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04doneB\a\n" +
	"\x05chunk\"\x8c\x02\n" +
	"\n" +
	"PTYRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\x120\n" +
	"\x03env\x18\x05 \x03(\v2\x1e.peersh.v1.PTYRequest.EnvEntryR\x03env\x12\x15\n" +
	"\x06pty_id\x18\x06 \x01(\x03R\x05ptyId\x12'\n" +
	"\x0freattach_handle\x18\a \x01(\tR\x0ereattachHandle\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x0ePTYReattachAck\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x1e\n" +
	"\bPTYInput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"3\n" +
	"\tPTYResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x1d\n" +
	"\aPTYData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"<\n" +
	"\aPTYExit\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xd8\x02\n" +
	"\bPTYFrame\x12+\n" +
	"\x05input\x18\x01 \x01(\v2\x13.peersh.v1.PTYInputH\x00R\x05input\x12.\n" +
	"\x06resize\x18\x02 \x01(\v2\x14.peersh.v1.PTYResizeH\x00R\x06resize\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x12.peersh.v1.PTYDataH\x00R\x04data\x12(\n" +
	"\x04exit\x18\x04 \x01(\v2\x12.peersh.v1.PTYExitH\x00R\x04exit\x12>\n" +
	"\freattach_ack\x18\x05 \x01(\v2\x19.peersh.v1.PTYReattachAckH\x00R\vreattachAck\x12S\n" +
	"\x13notification_config\x18\x06 \x01(\v2 .peersh.v1.PTYNotificationConfigH\x00R\x12notificationConfigB\x06\n" +
	"\x04kind\"\xc8\x01\n" +
	"\x15PTYNotificationConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12+\n" +
	"\x11threshold_seconds\x18\x02 \x01(\rR\x10thresholdSeconds\x12!\n" +
	"\fidle_seconds\x18\x03 \x01(\rR\vidleSeconds\x12\x1b\n" +
	"\ttab_label\x18\x04 \x01(\tR\btabLabel\x12(\n" +
	"\x10mobile_device_id\x18\x05 \x01(\tR\x0emobileDeviceId\"\xd1\x02\n" +
	"\fFilesRequest\x12?\n" +
	"\vget_session\x18\x01 \x01(\v2\x1c.peersh.v1.GetSessionRequestH\x00R\n" +
	"getSession\x12C\n" +
	"\n" +
	"list_files\x18\x02 \x01(\v2\".peersh.v1.ListSessionFilesRequestH\x00R\tlistFiles\x12@\n" +
	"\tread_file\x18\x03 \x01(\v2!.peersh.v1.ReadSessionFileRequestH\x00R\breadFile\x129\n" +
	"\tlist_ptys\x18\x04 \x01(\v2\x1a.peersh.v1.ListPTYsRequestH\x00R\blistPtys\x126\n" +
	"\bkill_pty\x18\x05 \x01(\v2\x19.peersh.v1.KillPTYRequestH\x00R\akillPtyB\x06\n" +
	"\x04kind\"\xf0\x02\n" +
	"\rFilesResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12@\n" +
	"\vget_session\x18\x02 \x01(\v2\x1d.peersh.v1.GetSessionResponseH\x00R\n" +
	"getSession\x12D\n" +
	"\n" +
	"list_files\x18\x03 \x01(\v2#.peersh.v1.ListSessionFilesResponseH\x00R\tlistFiles\x12A\n" +
	"\tread_file\x18\x04 \x01(\v2\".peersh.v1.ReadSessionFileResponseH\x00R\breadFile\x12:\n" +
	"\tlist_ptys\x18\x05 \x01(\v2\x1b.peersh.v1.ListPTYsResponseH\x00R\blistPtys\x127\n" +
	"\bkill_pty\x18\x06 \x01(\v2\x1a.peersh.v1.KillPTYResponseH\x00R\akillPtyB\t\n" +
	"\apayload\"(\n" +
	"\x0eKillPTYRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"!\n" +
	"\x0fKillPTYResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x11\n" +
	"\x0fListPTYsRequest\"\xbd\x01\n" +
	"\tPTYHandle\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1a\n" +
	"\battached\x18\x03 \x01(\bR\battached\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12)\n" +
	"\x11last_seen_unix_ms\x18\x05 \x01(\x03R\x0elastSeenUnixMs\x12%\n" +
	"\x0eattached_count\x18\x06 \x01(\rR\rattachedCount\"<\n" +
	"\x10ListPTYsResponse\x12(\n" +
	"\x04ptys\x18\x01 \x03(\v2\x14.peersh.v1.PTYHandleR\x04ptys\"*\n" +
	"\x11GetSessionRequest\x12\x15\n" +
	"\x06pty_id\x18\x01 \x01(\x03R\x05ptyId\"&\n" +
	"\x12GetSessionResponse\x12\x10\n" +
	"\x03cwd\x18\x01 \x01(\tR\x03cwd\"D\n" +
	"\x17ListSessionFilesRequest\x12\x15\n" +
	"\x06pty_id\x18\x01 \x01(\x03R\x05ptyId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x88\x01\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12(\n" +
	"\x10modified_unix_ms\x18\x05 \x01(\x03R\x0emodifiedUnixMs\"o\n" +
	"\x18ListSessionFilesResponse\x12#\n" +
	"\rresolved_path\x18\x01 \x01(\tR\fresolvedPath\x12.\n" +
	"\aentries\x18\x02 \x03(\v2\x14.peersh.v1.FileEntryR\aentries\"`\n" +
	"\x16ReadSessionFileRequest\x12\x15\n" +
	"\x06pty_id\x18\x01 \x01(\x03R\x05ptyId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1b\n" +
	"\tmax_bytes\x18\x03 \x01(\x03R\bmaxBytes\"\x81\x01\n" +
	"\x17ReadSessionFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1a\n" +
	"\bencoding\x18\x02 \x01(\tR\bencoding\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1c\n" +
	"\ttruncated\x18\x04 \x01(\bR\ttruncatedB\x9a\x01\n" +
	"\rcom.peersh.v1B\tExecProtoP\x01Z9github.com/peersh/peersh/core/protocol/peersh/v1;peershv1\xa2\x02\x03PXX\xaa\x02\tPeersh.V1\xca\x02\tPeersh\\V1\xe2\x02\x15Peersh\\V1\\GPBMetadata\xea\x02\n" +
	"Peersh::V1b\x06proto3"

var (
	file_peersh_v1_exec_proto_rawDescOnce sync.Once
	file_peersh_v1_exec_proto_rawDescData []byte
)

func file_peersh_v1_exec_proto_rawDescGZIP() []byte {
	file_peersh_v1_exec_proto_rawDescOnce.Do(func() {
		file_peersh_v1_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peersh_v1_exec_proto_rawDesc), len(file_peersh_v1_exec_proto_rawDesc)))
	})
	return file_peersh_v1_exec_proto_rawDescData
}

var file_peersh_v1_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_peersh_v1_exec_proto_goTypes = []any{
	(*StreamRequest)(nil),            // 0: peersh.v1.StreamRequest
	(*ExecRequest)(nil),              // 1: peersh.v1.ExecRequest
	(*ExecResponse)(nil),             // 2: peersh.v1.ExecResponse
	(*PTYRequest)(nil),               // 3: peersh.v1.PTYRequest
	(*PTYReattachAck)(nil),           // 4: peersh.v1.PTYReattachAck
	(*PTYInput)(nil),                 // 5: peersh.v1.PTYInput
	(*PTYResize)(nil),                // 6: peersh.v1.PTYResize
	(*PTYData)(nil),                  // 7: peersh.v1.PTYData
	(*PTYExit)(nil),                  // 8: peersh.v1.PTYExit
	(*PTYFrame)(nil),                 // 9: peersh.v1.PTYFrame
	(*PTYNotificationConfig)(nil),    // 10: peersh.v1.PTYNotificationConfig
	(*FilesRequest)(nil),             // 11: peersh.v1.FilesRequest
	(*FilesResponse)(nil),            // 12: peersh.v1.FilesResponse
	(*KillPTYRequest)(nil),           // 13: peersh.v1.KillPTYRequest
	(*KillPTYResponse)(nil),          // 14: peersh.v1.KillPTYResponse
	(*ListPTYsRequest)(nil),          // 15: peersh.v1.ListPTYsRequest
	(*PTYHandle)(nil),                // 16: peersh.v1.PTYHandle
	(*ListPTYsResponse)(nil),         // 17: peersh.v1.ListPTYsResponse
	(*GetSessionRequest)(nil),        // 18: peersh.v1.GetSessionRequest
	(*GetSessionResponse)(nil),       // 19: peersh.v1.GetSessionResponse
	(*ListSessionFilesRequest)(nil),  // 20: peersh.v1.ListSessionFilesRequest
	(*FileEntry)(nil),                // 21: peersh.v1.FileEntry
	(*ListSessionFilesResponse)(nil), // 22: peersh.v1.ListSessionFilesResponse
	(*ReadSessionFileRequest)(nil),   // 23: peersh.v1.ReadSessionFileRequest
	(*ReadSessionFileResponse)(nil),  // 24: peersh.v1.ReadSessionFileResponse
	nil,                              // 25: peersh.v1.PTYRequest.EnvEntry
}
var file_peersh_v1_exec_proto_depIdxs = []int32{
	1,  // 0: peersh.v1.StreamRequest.exec:type_name -> peersh.v1.ExecRequest
	3,  // 1: peersh.v1.StreamRequest.pty:type_name -> peersh.v1.PTYRequest
	11, // 2: peersh.v1.StreamRequest.files:type_name -> peersh.v1.FilesRequest
	25, // 3: peersh.v1.PTYRequest.env:type_name -> peersh.v1.PTYRequest.EnvEntry
	5,  // 4: peersh.v1.PTYFrame.input:type_name -> peersh.v1.PTYInput
	6,  // 5: peersh.v1.PTYFrame.resize:type_name -> peersh.v1.PTYResize
	7,  // 6: peersh.v1.PTYFrame.data:type_name -> peersh.v1.PTYData
	8,  // 7: peersh.v1.PTYFrame.exit:type_name -> peersh.v1.PTYExit
	4,  // 8: peersh.v1.PTYFrame.reattach_ack:type_name -> peersh.v1.PTYReattachAck
	10, // 9: peersh.v1.PTYFrame.notification_config:type_name -> peersh.v1.PTYNotificationConfig
	18, // 10: peersh.v1.FilesRequest.get_session:type_name -> peersh.v1.GetSessionRequest
	20, // 11: peersh.v1.FilesRequest.list_files:type_name -> peersh.v1.ListSessionFilesRequest
	23, // 12: peersh.v1.FilesRequest.read_file:type_name -> peersh.v1.ReadSessionFileRequest
	15, // 13: peersh.v1.FilesRequest.list_ptys:type_name -> peersh.v1.ListPTYsRequest
	13, // 14: peersh.v1.FilesRequest.kill_pty:type_name -> peersh.v1.KillPTYRequest
	19, // 15: peersh.v1.FilesResponse.get_session:type_name -> peersh.v1.GetSessionResponse
	22, // 16: peersh.v1.FilesResponse.list_files:type_name -> peersh.v1.ListSessionFilesResponse
	24, // 17: peersh.v1.FilesResponse.read_file:type_name -> peersh.v1.ReadSessionFileResponse
	17, // 18: peersh.v1.FilesResponse.list_ptys:type_name -> peersh.v1.ListPTYsResponse
	14, // 19: peersh.v1.FilesResponse.kill_pty:type_name -> peersh.v1.KillPTYResponse
	16, // 20: peersh.v1.ListPTYsResponse.ptys:type_name -> peersh.v1.PTYHandle
	21, // 21: peersh.v1.ListSessionFilesResponse.entries:type_name -> peersh.v1.FileEntry
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_peersh_v1_exec_proto_init() }
func file_peersh_v1_exec_proto_init() {
	if File_peersh_v1_exec_proto != nil {
		return
	}
	file_peersh_v1_exec_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamRequest_Exec)(nil),
		(*StreamRequest_Pty)(nil),
		(*StreamRequest_Files)(nil),
	}
	file_peersh_v1_exec_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecResponse_Stdout)(nil),
		(*ExecResponse_Stderr)(nil),
	}
	file_peersh_v1_exec_proto_msgTypes[9].OneofWrappers = []any{
		(*PTYFrame_Input)(nil),
		(*PTYFrame_Resize)(nil),
		(*PTYFrame_Data)(nil),
		(*PTYFrame_Exit)(nil),
		(*PTYFrame_ReattachAck)(nil),
		(*PTYFrame_NotificationConfig)(nil),
	}
	file_peersh_v1_exec_proto_msgTypes[11].OneofWrappers = []any{
		(*FilesRequest_GetSession)(nil),
		(*FilesRequest_ListFiles)(nil),
		(*FilesRequest_ReadFile)(nil),
		(*FilesRequest_ListPtys)(nil),
		(*FilesRequest_KillPty)(nil),
	}
	file_peersh_v1_exec_proto_msgTypes[12].OneofWrappers = []any{
		(*FilesResponse_GetSession)(nil),
		(*FilesResponse_ListFiles)(nil),
		(*FilesResponse_ReadFile)(nil),
		(*FilesResponse_ListPtys)(nil),
		(*FilesResponse_KillPty)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peersh_v1_exec_proto_rawDesc), len(file_peersh_v1_exec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peersh_v1_exec_proto_goTypes,
		DependencyIndexes: file_peersh_v1_exec_proto_depIdxs,
		MessageInfos:      file_peersh_v1_exec_proto_msgTypes,
	}.Build()
	File_peersh_v1_exec_proto = out.File
	file_peersh_v1_exec_proto_goTypes = nil
	file_peersh_v1_exec_proto_depIdxs = nil
}
