// Per-command (and per-PTY) bidi streams opened after the control stream's
// Hello handshake completes.
//
// Every fresh stream begins with a StreamRequest envelope so the server can
// dispatch between the one-shot Exec path (Phase 1) and the interactive PTY
// path (Phase 8). The two paths share the underlying QUIC transport but
// have distinct response shapes.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: peersh/v1/exec.proto

package peershv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamRequest is the first frame on a fresh stream. The populated `kind`
// determines how the server treats subsequent frames on the stream.
type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*StreamRequest_Exec
	//	*StreamRequest_Pty
	Kind          isStreamRequest_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_peersh_v1_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetKind() isStreamRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *StreamRequest) GetExec() *ExecRequest {
	if x != nil {
		if x, ok := x.Kind.(*StreamRequest_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *StreamRequest) GetPty() *PTYRequest {
	if x != nil {
		if x, ok := x.Kind.(*StreamRequest_Pty); ok {
			return x.Pty
		}
	}
	return nil
}

type isStreamRequest_Kind interface {
	isStreamRequest_Kind()
}

type StreamRequest_Exec struct {
	Exec *ExecRequest `protobuf:"bytes,1,opt,name=exec,proto3,oneof"`
}

type StreamRequest_Pty struct {
	Pty *PTYRequest `protobuf:"bytes,2,opt,name=pty,proto3,oneof"`
}

func (*StreamRequest_Exec) isStreamRequest_Kind() {}

func (*StreamRequest_Pty) isStreamRequest_Kind() {}

// ExecRequest runs a single command and streams its output back. Used by
// peersh-cli's prompt loop and the mobile app's text viewer (ReadFile is
// implemented as Exec under the hood).
type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command is the PowerShell expression to execute. Treated as a single
	// pipeline; the host appends a sentinel marker to detect completion.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// working_dir, if non-empty, is set as the current working directory for
	// this command only. Empty means "use the session's current directory".
	// Reserved in Phase 1; implemented by the cwd-aware ReadFile path in
	// Phase 8 Tier 2.
	WorkingDir    string `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_peersh_v1_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{1}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

// ExecResponse carries either a chunk of output or the end-of-command signal.
// One ExecRequest produces a stream of ExecResponse messages, with the final
// message having done = true.
type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chunk holds streamed output bytes. Exactly one of stdout / stderr is set
	// on any non-final message; both may be unset on the final done = true
	// message.
	//
	// Types that are valid to be assigned to Chunk:
	//
	//	*ExecResponse_Stdout
	//	*ExecResponse_Stderr
	Chunk isExecResponse_Chunk `protobuf_oneof:"chunk"`
	// done signals end-of-command. The stream is closed after this message.
	Done          bool `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_peersh_v1_exec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{2}
}

func (x *ExecResponse) GetChunk() isExecResponse_Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Chunk.(*ExecResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Chunk.(*ExecResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type isExecResponse_Chunk interface {
	isExecResponse_Chunk()
}

type ExecResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

func (*ExecResponse_Stdout) isExecResponse_Chunk() {}

func (*ExecResponse_Stderr) isExecResponse_Chunk() {}

// PTYRequest opens a pseudo-console-backed shell or program on the host.
// After the server acks (by starting to send PTYData frames), the client
// streams keystrokes as PTYInput frames and resize notifications as
// PTYResize frames; the server streams PTYData frames carrying raw output
// (ANSI sequences and all) and finally a single PTYExit terminator.
type PTYRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command, when non-empty, is the executable to spawn (e.g. "claude").
	// Empty means "use the operator-configured default shell" — usually
	// pwsh wrapped with the OSC 9;9 prompt instrumentation.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// args are the command-line arguments passed verbatim. Ignored when
	// command is empty (the server picks the default shell wrapper).
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// cols and rows are the initial terminal grid the client wants the
	// pseudo-console sized to.
	Cols uint32 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows uint32 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	// env carries supplementary environment variables (e.g. TERM=xterm-256color).
	// The host process inherits the peershd environment plus these overrides.
	Env           map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYRequest) Reset() {
	*x = PTYRequest{}
	mi := &file_peersh_v1_exec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYRequest) ProtoMessage() {}

func (x *PTYRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYRequest.ProtoReflect.Descriptor instead.
func (*PTYRequest) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{3}
}

func (x *PTYRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *PTYRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *PTYRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PTYRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *PTYRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// PTYInput delivers a chunk of bytes from the user's keyboard / paste
// buffer to the child process's stdin.
type PTYInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYInput) Reset() {
	*x = PTYInput{}
	mi := &file_peersh_v1_exec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYInput) ProtoMessage() {}

func (x *PTYInput) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYInput.ProtoReflect.Descriptor instead.
func (*PTYInput) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{4}
}

func (x *PTYInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PTYResize tells the child the terminal grid dimensions changed.
// Programs that re-flow on SIGWINCH (or its Windows equivalent) react.
type PTYResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYResize) Reset() {
	*x = PTYResize{}
	mi := &file_peersh_v1_exec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYResize) ProtoMessage() {}

func (x *PTYResize) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYResize.ProtoReflect.Descriptor instead.
func (*PTYResize) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{5}
}

func (x *PTYResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PTYResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// PTYData carries raw output bytes from the child's pseudo-console.
// ConPTY merges stdout/stderr into a single byte stream, so unlike
// ExecResponse there is no separate channel tagging.
type PTYData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYData) Reset() {
	*x = PTYData{}
	mi := &file_peersh_v1_exec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYData) ProtoMessage() {}

func (x *PTYData) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYData.ProtoReflect.Descriptor instead.
func (*PTYData) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{6}
}

func (x *PTYData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PTYExit terminates the PTY stream. After PTYExit the server closes the
// stream and any further client frames are discarded.
type PTYExit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// exit_code mirrors the child process's exit status. -1 indicates an
	// unknown / abnormal exit (e.g. peersh killed the process to satisfy
	// an idle timeout).
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// error, when non-empty, describes a server-side failure (spawn error,
	// pseudo-console allocation failure, ...).
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYExit) Reset() {
	*x = PTYExit{}
	mi := &file_peersh_v1_exec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYExit) ProtoMessage() {}

func (x *PTYExit) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYExit.ProtoReflect.Descriptor instead.
func (*PTYExit) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{7}
}

func (x *PTYExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *PTYExit) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PTYFrame multiplexes the four direction-specific message types onto the
// single QUIC stream. Client → server frames use the input / resize fields;
// server → client frames use the data / exit fields.
type PTYFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*PTYFrame_Input
	//	*PTYFrame_Resize
	//	*PTYFrame_Data
	//	*PTYFrame_Exit
	Kind          isPTYFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYFrame) Reset() {
	*x = PTYFrame{}
	mi := &file_peersh_v1_exec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYFrame) ProtoMessage() {}

func (x *PTYFrame) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYFrame.ProtoReflect.Descriptor instead.
func (*PTYFrame) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{8}
}

func (x *PTYFrame) GetKind() isPTYFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *PTYFrame) GetInput() *PTYInput {
	if x != nil {
		if x, ok := x.Kind.(*PTYFrame_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *PTYFrame) GetResize() *PTYResize {
	if x != nil {
		if x, ok := x.Kind.(*PTYFrame_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *PTYFrame) GetData() *PTYData {
	if x != nil {
		if x, ok := x.Kind.(*PTYFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *PTYFrame) GetExit() *PTYExit {
	if x != nil {
		if x, ok := x.Kind.(*PTYFrame_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isPTYFrame_Kind interface {
	isPTYFrame_Kind()
}

type PTYFrame_Input struct {
	Input *PTYInput `protobuf:"bytes,1,opt,name=input,proto3,oneof"`
}

type PTYFrame_Resize struct {
	Resize *PTYResize `protobuf:"bytes,2,opt,name=resize,proto3,oneof"`
}

type PTYFrame_Data struct {
	Data *PTYData `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type PTYFrame_Exit struct {
	Exit *PTYExit `protobuf:"bytes,4,opt,name=exit,proto3,oneof"`
}

func (*PTYFrame_Input) isPTYFrame_Kind() {}

func (*PTYFrame_Resize) isPTYFrame_Kind() {}

func (*PTYFrame_Data) isPTYFrame_Kind() {}

func (*PTYFrame_Exit) isPTYFrame_Kind() {}

var File_peersh_v1_exec_proto protoreflect.FileDescriptor

const file_peersh_v1_exec_proto_rawDesc = "" +
	"\n" +
	"\x14peersh/v1/exec.proto\x12\tpeersh.v1\"p\n" +
	"\rStreamRequest\x12,\n" +
	"\x04exec\x18\x01 \x01(\v2\x16.peersh.v1.ExecRequestH\x00R\x04exec\x12)\n" +
	"\x03pty\x18\x02 \x01(\v2\x15.peersh.v1.PTYRequestH\x00R\x03ptyB\x06\n" +
	"\x04kind\"H\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\"_\n" +
	"\fExecResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04doneB\a\n" +
	"\x05chunk\"\xcc\x01\n" +
	"\n" +
	"PTYRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\x120\n" +
	"\x03env\x18\x05 \x03(\v2\x1e.peersh.v1.PTYRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1e\n" +
	"\bPTYInput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"3\n" +
	"\tPTYResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x1d\n" +
	"\aPTYData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"<\n" +
	"\aPTYExit\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc3\x01\n" +
	"\bPTYFrame\x12+\n" +
	"\x05input\x18\x01 \x01(\v2\x13.peersh.v1.PTYInputH\x00R\x05input\x12.\n" +
	"\x06resize\x18\x02 \x01(\v2\x14.peersh.v1.PTYResizeH\x00R\x06resize\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x12.peersh.v1.PTYDataH\x00R\x04data\x12(\n" +
	"\x04exit\x18\x04 \x01(\v2\x12.peersh.v1.PTYExitH\x00R\x04exitB\x06\n" +
	"\x04kindB\x9a\x01\n" +
	"\rcom.peersh.v1B\tExecProtoP\x01Z9github.com/peersh/peersh/core/protocol/peersh/v1;peershv1\xa2\x02\x03PXX\xaa\x02\tPeersh.V1\xca\x02\tPeersh\\V1\xe2\x02\x15Peersh\\V1\\GPBMetadata\xea\x02\n" +
	"Peersh::V1b\x06proto3"

var (
	file_peersh_v1_exec_proto_rawDescOnce sync.Once
	file_peersh_v1_exec_proto_rawDescData []byte
)

func file_peersh_v1_exec_proto_rawDescGZIP() []byte {
	file_peersh_v1_exec_proto_rawDescOnce.Do(func() {
		file_peersh_v1_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peersh_v1_exec_proto_rawDesc), len(file_peersh_v1_exec_proto_rawDesc)))
	})
	return file_peersh_v1_exec_proto_rawDescData
}

var file_peersh_v1_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_peersh_v1_exec_proto_goTypes = []any{
	(*StreamRequest)(nil), // 0: peersh.v1.StreamRequest
	(*ExecRequest)(nil),   // 1: peersh.v1.ExecRequest
	(*ExecResponse)(nil),  // 2: peersh.v1.ExecResponse
	(*PTYRequest)(nil),    // 3: peersh.v1.PTYRequest
	(*PTYInput)(nil),      // 4: peersh.v1.PTYInput
	(*PTYResize)(nil),     // 5: peersh.v1.PTYResize
	(*PTYData)(nil),       // 6: peersh.v1.PTYData
	(*PTYExit)(nil),       // 7: peersh.v1.PTYExit
	(*PTYFrame)(nil),      // 8: peersh.v1.PTYFrame
	nil,                   // 9: peersh.v1.PTYRequest.EnvEntry
}
var file_peersh_v1_exec_proto_depIdxs = []int32{
	1, // 0: peersh.v1.StreamRequest.exec:type_name -> peersh.v1.ExecRequest
	3, // 1: peersh.v1.StreamRequest.pty:type_name -> peersh.v1.PTYRequest
	9, // 2: peersh.v1.PTYRequest.env:type_name -> peersh.v1.PTYRequest.EnvEntry
	4, // 3: peersh.v1.PTYFrame.input:type_name -> peersh.v1.PTYInput
	5, // 4: peersh.v1.PTYFrame.resize:type_name -> peersh.v1.PTYResize
	6, // 5: peersh.v1.PTYFrame.data:type_name -> peersh.v1.PTYData
	7, // 6: peersh.v1.PTYFrame.exit:type_name -> peersh.v1.PTYExit
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_peersh_v1_exec_proto_init() }
func file_peersh_v1_exec_proto_init() {
	if File_peersh_v1_exec_proto != nil {
		return
	}
	file_peersh_v1_exec_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamRequest_Exec)(nil),
		(*StreamRequest_Pty)(nil),
	}
	file_peersh_v1_exec_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecResponse_Stdout)(nil),
		(*ExecResponse_Stderr)(nil),
	}
	file_peersh_v1_exec_proto_msgTypes[8].OneofWrappers = []any{
		(*PTYFrame_Input)(nil),
		(*PTYFrame_Resize)(nil),
		(*PTYFrame_Data)(nil),
		(*PTYFrame_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peersh_v1_exec_proto_rawDesc), len(file_peersh_v1_exec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peersh_v1_exec_proto_goTypes,
		DependencyIndexes: file_peersh_v1_exec_proto_depIdxs,
		MessageInfos:      file_peersh_v1_exec_proto_msgTypes,
	}.Build()
	File_peersh_v1_exec_proto = out.File
	file_peersh_v1_exec_proto_goTypes = nil
	file_peersh_v1_exec_proto_depIdxs = nil
}
