// Exec messages flow on per-command bidi streams opened after the control
// stream's Hello handshake completes. Each fresh stream begins with one
// ExecRequest from the client; the server then streams ExecResponse messages
// until done = true.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: peersh/v1/exec.proto

package peershv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecRequest is the first message on a fresh per-command stream.
type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command is the PowerShell expression to execute. Treated as a single
	// pipeline; the host may append a sentinel marker to detect completion.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// working_dir, if non-empty, is set as the current working directory for
	// this command only. Empty means "use the session's current directory".
	// Phase 1 does not implement directory switching; this field is reserved.
	WorkingDir    string `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_peersh_v1_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

// ExecResponse carries either a chunk of output or the end-of-command signal.
// One ExecRequest produces a stream of ExecResponse messages, with the final
// message having done = true.
type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chunk holds streamed output bytes. Exactly one of stdout / stderr is set
	// on any non-final message; both may be unset on the final done = true
	// message.
	//
	// Types that are valid to be assigned to Chunk:
	//
	//	*ExecResponse_Stdout
	//	*ExecResponse_Stderr
	Chunk isExecResponse_Chunk `protobuf_oneof:"chunk"`
	// done signals end-of-command. The stream is closed after this message.
	Done          bool `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_peersh_v1_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_peersh_v1_exec_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResponse) GetChunk() isExecResponse_Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Chunk.(*ExecResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Chunk.(*ExecResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type isExecResponse_Chunk interface {
	isExecResponse_Chunk()
}

type ExecResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

func (*ExecResponse_Stdout) isExecResponse_Chunk() {}

func (*ExecResponse_Stderr) isExecResponse_Chunk() {}

var File_peersh_v1_exec_proto protoreflect.FileDescriptor

const file_peersh_v1_exec_proto_rawDesc = "" +
	"\n" +
	"\x14peersh/v1/exec.proto\x12\tpeersh.v1\"H\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\"_\n" +
	"\fExecResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04doneB\a\n" +
	"\x05chunkB\x9a\x01\n" +
	"\rcom.peersh.v1B\tExecProtoP\x01Z9github.com/peersh/peersh/core/protocol/peersh/v1;peershv1\xa2\x02\x03PXX\xaa\x02\tPeersh.V1\xca\x02\tPeersh\\V1\xe2\x02\x15Peersh\\V1\\GPBMetadata\xea\x02\n" +
	"Peersh::V1b\x06proto3"

var (
	file_peersh_v1_exec_proto_rawDescOnce sync.Once
	file_peersh_v1_exec_proto_rawDescData []byte
)

func file_peersh_v1_exec_proto_rawDescGZIP() []byte {
	file_peersh_v1_exec_proto_rawDescOnce.Do(func() {
		file_peersh_v1_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peersh_v1_exec_proto_rawDesc), len(file_peersh_v1_exec_proto_rawDesc)))
	})
	return file_peersh_v1_exec_proto_rawDescData
}

var file_peersh_v1_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_peersh_v1_exec_proto_goTypes = []any{
	(*ExecRequest)(nil),  // 0: peersh.v1.ExecRequest
	(*ExecResponse)(nil), // 1: peersh.v1.ExecResponse
}
var file_peersh_v1_exec_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_peersh_v1_exec_proto_init() }
func file_peersh_v1_exec_proto_init() {
	if File_peersh_v1_exec_proto != nil {
		return
	}
	file_peersh_v1_exec_proto_msgTypes[1].OneofWrappers = []any{
		(*ExecResponse_Stdout)(nil),
		(*ExecResponse_Stderr)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peersh_v1_exec_proto_rawDesc), len(file_peersh_v1_exec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peersh_v1_exec_proto_goTypes,
		DependencyIndexes: file_peersh_v1_exec_proto_depIdxs,
		MessageInfos:      file_peersh_v1_exec_proto_msgTypes,
	}.Build()
	File_peersh_v1_exec_proto = out.File
	file_peersh_v1_exec_proto_goTypes = nil
	file_peersh_v1_exec_proto_depIdxs = nil
}
