// Hello messages exchanged on the peersh control stream (QUIC client-initiated
// bidi stream 0) immediately after the QUIC handshake. Carry the protocol
// version and capability advertisements that gate every subsequent
// application stream on the same connection.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: peersh/v1/hello.proto

package peershv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientHello is sent by the client right after opening the control stream.
type ClientHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol_version is bumped only for breaking wire-format changes.
	// The current QUIC application protocol version is 2.
	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// capabilities advertise optional, additive features. Examples that may
	// appear in later phases: "session_resume", "ipv6". Empty in Phase 1.
	Capabilities []string `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// client_id is a free-form identifier string (e.g. "peersh-cli/0.1").
	// Servers may log it but must not trust it for authorization.
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// session_id requests reattach to a previously-assigned session.
	// Empty for "give me a fresh session". Added in Phase 6. The host may
	// refuse the reattach (session expired, unknown id, server restart);
	// ServerHello.reattached reports the outcome.
	SessionId string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// idle_timeout_sec is the client's preferred lifetime for detached
	// sessions and PTYs on the host. 0 means "use the host default"
	// (currently 24h). The host may clamp to its own minimum/maximum.
	// Applies to both pwsh.SessionManager and ptyhost.Manager. Added so
	// mobile clients can opt into longer-lived shells that survive OS
	// backgrounding without the user re-pairing.
	IdleTimeoutSec uint32 `protobuf:"varint,5,opt,name=idle_timeout_sec,json=idleTimeoutSec,proto3" json:"idle_timeout_sec,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_peersh_v1_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_peersh_v1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ClientHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ClientHello) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientHello) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientHello) GetIdleTimeoutSec() uint32 {
	if x != nil {
		return x.IdleTimeoutSec
	}
	return 0
}

// ServerHello is the server's response on the control stream.
type ServerHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ServerId        string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// session_id is the host-assigned session identifier the client should
	// present on subsequent reconnects via ClientHello.session_id. Phase 6.
	SessionId string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// reattached is true when the host successfully attached to an
	// existing session matching the client's requested session_id. False
	// for fresh sessions (either no session_id was requested, or the
	// requested one was unknown / expired).
	Reattached    bool `protobuf:"varint,5,opt,name=reattached,proto3" json:"reattached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_peersh_v1_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_peersh_v1_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_peersh_v1_hello_proto_rawDescGZIP(), []int{1}
}

func (x *ServerHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ServerHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ServerHello) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerHello) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ServerHello) GetReattached() bool {
	if x != nil {
		return x.Reattached
	}
	return false
}

var File_peersh_v1_hello_proto protoreflect.FileDescriptor

const file_peersh_v1_hello_proto_rawDesc = "" +
	"\n" +
	"\x15peersh/v1/hello.proto\x12\tpeersh.v1\"\xc2\x01\n" +
	"\vClientHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12(\n" +
	"\x10idle_timeout_sec\x18\x05 \x01(\rR\x0eidleTimeoutSec\"\xb8\x01\n" +
	"\vServerHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"reattached\x18\x05 \x01(\bR\n" +
	"reattachedB\x9b\x01\n" +
	"\rcom.peersh.v1B\n" +
	"HelloProtoP\x01Z9github.com/peersh/peersh/core/protocol/peersh/v1;peershv1\xa2\x02\x03PXX\xaa\x02\tPeersh.V1\xca\x02\tPeersh\\V1\xe2\x02\x15Peersh\\V1\\GPBMetadata\xea\x02\n" +
	"Peersh::V1b\x06proto3"

var (
	file_peersh_v1_hello_proto_rawDescOnce sync.Once
	file_peersh_v1_hello_proto_rawDescData []byte
)

func file_peersh_v1_hello_proto_rawDescGZIP() []byte {
	file_peersh_v1_hello_proto_rawDescOnce.Do(func() {
		file_peersh_v1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peersh_v1_hello_proto_rawDesc), len(file_peersh_v1_hello_proto_rawDesc)))
	})
	return file_peersh_v1_hello_proto_rawDescData
}

var file_peersh_v1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_peersh_v1_hello_proto_goTypes = []any{
	(*ClientHello)(nil), // 0: peersh.v1.ClientHello
	(*ServerHello)(nil), // 1: peersh.v1.ServerHello
}
var file_peersh_v1_hello_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_peersh_v1_hello_proto_init() }
func file_peersh_v1_hello_proto_init() {
	if File_peersh_v1_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peersh_v1_hello_proto_rawDesc), len(file_peersh_v1_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peersh_v1_hello_proto_goTypes,
		DependencyIndexes: file_peersh_v1_hello_proto_depIdxs,
		MessageInfos:      file_peersh_v1_hello_proto_msgTypes,
	}.Build()
	File_peersh_v1_hello_proto = out.File
	file_peersh_v1_hello_proto_goTypes = nil
	file_peersh_v1_hello_proto_depIdxs = nil
}
